#ifndef _TOY_PROTOCAL_H_
#define _TOY_PROTOCAL_H_

enum PACK_TYPE
{
	PT_USER  					= 0,
	PT_HAVE_LOGINED 				= 128,
	PT_USER_NOEXIST				= 129,
	PT_REQU_PWDHASH				= 130,
	PT_PWDHASH 					= 1,
	PT_WRONG_PWD					= 131,
	PT_LOGIN_SUCCEED				= 132,
	PT_LOGOUT					= 2,
	PT_LOGOUT_SUCCEED			= 133,
	PT_UPLOAD					= 3,
	PT_UPLOAD_ESTABLISH			= 134,
	PT_REGISTER					= 4,
	PT_REGISTER_SUCCEED			= 135,
	PT_HAVE_EXISTED				= 136,
	PT_LIST						= 5,
	PT_DOWNLOAD					= 6, 
	PT_DOWNLOAD_ESTABLISH		= 137
};

//#define BLOCK_SIZE			67108864				// 64 MB = 67108864 Bytes
#define BLOCK_SIZE		8192

#endif // _TOY_PROTOCAL_H_